### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by ricoms** [tradingstrategy-ai/tqdm-loggable#2]
Initially this package worked for me, I was able to use it inside a local docker application, and worked correctly.

But when I was trying to `set_log_rate` it stoped working and gave me the following error:

```
» python scripts/tqdm.py              
Traceback (most recent call last):
  File "/Users/ricardosavii/workspace/jewelml/jewel-ml-models/scripts/tqdm.py", line 5, in <module>
    from tqdm_loggable.auto import tqdm
  File "/Users/ricardosavii/Library/Caches/pypoetry/virtualenvs/jewel-ml-models-GrvoSmEm-py3.10/lib/python3.10/site-packages/tqdm_loggable/auto.py", line 4, in <module>
    from tqdm.auto import tqdm
  File "/Users/ricardosavii/workspace/jewelml/jewel-ml-models/scripts/tqdm.py", line 5, in <module>
    from tqdm_loggable.auto import tqdm
ImportError: cannot import name 'tqdm' from partially initialized module 'tqdm_loggable.auto' (most likely due to a circular import) (/Users/ricardosavii/Library/Caches/pypoetry/virtualenvs/jewel-ml-models-GrvoSmEm-py3.10/lib/python3.10/site-packages/tqdm_loggable/auto.py)
```

I tested it out running this simple script:

```
from datetime import timedelta

from tqdm_loggable.auto import tqdm
from tqdm_loggable.tqdm_logging import tqdm_logging

if __name__=="__main__":
    tqdm_logging.set_log_rate(timedelta(seconds=2))
    for i in tqdm(range(10000000)):
        i = True

```

I also teste it with you documentation given example and I get the same error. Your doc example is:

```
import datetime
import logging
import time

from tqdm_loggable.auto import tqdm
from tqdm_loggable.tqdm_logging import tqdm_logging


logger = logging.getLogger(__name__)


def main():
    fmt = f"%(filename)-20s:%(lineno)-4d %(asctime)s %(message)s"
    logging.basicConfig(level=logging.INFO, format=fmt, handlers=[logging.StreamHandler()])

    # Set the log level to all tqdm-logging progress bars.
    # Defaults to info - no need to set if you do not want to change the level
    tqdm_logging.set_level(logging.INFO)
    
    # Set the rate how often we update logs
    # Defaults to 10 seconds - optional
    tqdm_logging.set_log_rate(datetime.timedelta(seconds=10))

    logger.info("This is an INFO test message using Python logging")

    with tqdm(total=60_000, desc="Sample progress", unit_scale=True) as progress_bar:
        for i in range(60_000):
            progress_bar.update(1000)

            # Test postfix output
            progress_bar.set_postfix({"Current time": datetime.datetime.utcnow()})

            time.sleep(0.5)
```

**Comment by miohtama** [comment]
Hi.

Sorry for late response time, I did not see the issue.

How do you install the package? I suspect there is some sort of a conflict between different `tqdm` namespaces, because your script is called `tqdm.py`. Can you try with a different script name?
